package pojos;
// Generated Jun 25, 2018 7:41:24 PM by Hibernate Tools 4.3.1



/**
 * Artist generated by hbm2java
 */
public class Artist  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Artist() {
    }

    public Artist(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


